//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
		public class AnimationControl
		{
			public Animator anim;
			
			// Animations ID
			public string walk_f = "walk_forward";
			public string walk_b = "walk_backward";
			public string punch = "punch";
			public string idle = "idle";
			
			// Constructor
			public AnimationControl( Animator a)
			{
				anim = a;
			}
			
			public bool inAttackStance()
			{
				if (anim.GetCurrentAnimatorStateInfo(0).IsName("Punch"))
					return true;
				return false;
			}
			public bool inMoveStance()
			{
				if (anim.GetCurrentAnimatorStateInfo(0).IsName("WalkForward"))
					return true;
				if (anim.GetCurrentAnimatorStateInfo(0).IsName("WalkBackward"))
					return true;
				return false;
			}
			public void initParameters()
			{
				setWalkF (false);
				setWalkB (false);
			}
			
			public void setWalkF(bool value){
				anim.SetBool (walk_f, value);
			}
			public void setWalkB(bool value){
				anim.SetBool (walk_b, value);
			}
			public void setIdle(bool value){
				anim.SetBool (idle, value);
			}
			public void setPunch(){
				//anim.SetTrigger (punch);
				anim.CrossFade("Punch",0);
			}
		}
}

