//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
		public class AnimationControl
		{
			public Animator anim;
			
			// direction ID
			public const float BACKWARD = -1;
			public const float FORWARD = 1;
			public const float NULL = 0;
			// Parameters ID
			public string direction = "direction";
			public string isGrounded = "isGrounded";
			public string isMoving = "isMoving";
			public string fall = "fall";
		public string jump = "jump";
		public string dash = "dash";
			public string punch = "punch";
			public string idle = "idle";
			
			// Constructor
			public AnimationControl( Animator a)
			{
				anim = a;
			}
			
			public bool inAttackStance()
			{
				if (anim.GetCurrentAnimatorStateInfo(0).IsName("Punch"))
					return true;
				return false;
			}
			public bool inMoveStance()
			{
				if (anim.GetCurrentAnimatorStateInfo(0).IsName("Walk"))
					return true;
				return false;
		}
			public bool inAirDashStance()
			{
				if (anim.GetCurrentAnimatorStateInfo(0).IsName("AirDash"))
					return true;
				return false;
			}
			public void initParameters()
			{
				setDirection(NULL);
			}
		public void setIdle(bool value){
			anim.SetBool (idle, value);
		}
		public void setDash(bool value){
			anim.SetBool (dash, value);
		}
			public void setJump(){
				anim.SetTrigger (jump);
		}
		public void setFall(bool value){
			anim.SetBool (fall, value);
		}
		public void setIsGrounded(bool value){
			anim.SetBool (isGrounded, value);
		}
		public void setIsMoving(bool value){
			anim.SetBool (isMoving, value);
		}
			public void setDirection(float dir){
				anim.SetFloat (direction,dir);
		}
			public void setPunch(){
				//anim.SetTrigger (punch);
				anim.CrossFade("Punch",0);
			}
		}
}

