//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Assertion
	{
        public enum Condition { GROUND, AIR, PV_OVER_50, SP_NEED_1, SP_COST_1 }
        public Condition[] preCondition;
        public Condition[] postCondition;
        public Assertion(Condition[] preCondition)
        {
            this.preCondition = preCondition;
        }
        public Assertion(Condition[] preCondition, Condition[] postCondition)
        {
            this.preCondition = preCondition;
            this.postCondition = postCondition;
        }

        public bool checkPreCondition(Player p)
        {
            bool valid = false;
            foreach(Condition condition in preCondition)
            {
                switch(condition)
                {
                    case Condition.GROUND:
                        valid = p.isGrounded;
                        break;
                    case Condition.AIR:
                        valid = !p.isGrounded;
                        break;
                    case Condition.PV_OVER_50:
                        valid = p.currentPV > (p.PVMax/2);
                        break;
                    default:
                        valid = true;
                        break;
                }
                if (!valid) return false;
            }
            return true;
        }
        public Player setPostCondition(Player p)
        {
            if(postCondition == null) return p;
            foreach (Condition condition in postCondition)
            {
                switch (condition)
                {
                    case Condition.SP_COST_1:
                        p.currentPV = p.currentSP-1;
                        break;
                    default:
                        break;
                }
            }
            return p;
        }
	}
}

