//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Character
	{
        public Command[] commandList;
        public int mass = 1;
        public float walkSpeed;
        public float runSpeed;
        public bool canRun;
        public string name;
        public float PV;
        public int SPMax;

        public Character()
        {
            commandList = new Command[]
            {
                new Command(GameButton.WEAK, 0.5f, 0, AnimationControl.weak),
				new Command(GameButton.MEDIUM, 0.5f, 0, AnimationControl.medium),
				new Command(GameButton.STRONG, 0.5f, 0, AnimationControl.strong)
            };

            /*
            public Command medium;
            public Command strong;
            public Command special;
            public Command unique1;
            public Command unique2;
            public Command unique3;
            public Command unique4;
            public Command unique5;
            public Command unique6;*/
        }
	}
}

