//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Command
	{
        public GameButton button;
        public GameButton[][] combinationKey;
        public bool isCombination;
        public bool isActive;
		public float duration = 0;
        public int counter = 0;
        public float damage = 0;
		public string name = "";
        public string description;
        public Assertion condition;
        public string launcher = "";

        public void incrementCounter()
        {
			if (!isCombination)return;
            if(counter >= combinationKey.GetLength(0))
            {
                counter = 0;
            }
            else { counter ++; }
        }

        public Command(GameButton[][] combinationKey, float duration, int damage,string launcher)
        {
            this.combinationKey = combinationKey;
            this.isCombination = true;
            this.duration = duration;
            this.damage = damage;
            this.launcher = launcher;
        }
        public Command(GameButton[][] combinationKey, Assertion condition, string launcher)
        {
            this.combinationKey = combinationKey;
            this.isCombination = true;
            this.duration = 0;
            this.damage = 0;
            this.condition = condition;
        }
        public Command(GameButton button, float duration, int damage, string launcher)
        {

            this.button = button;
            this.isCombination = false;
            this.duration = duration;
            this.damage = damage;
            this.launcher = launcher;
        }
	}
}

