//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Global
	{
		
		public const int UP = 1;
		public const int DOWN = -1;
		public const int LEFT = -1;
		public const int RIGHT = 1;
		public const int NONE = 0;
		
		
		public const int HIGH = 1;
		public const int MIDDLE = 2;
		public const int LOW = 3;
	}
}

