//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public enum Direction
	{
		
		UP = 1,DOWN = -1, LEFT = -1,RIGHT = 1,NONE = 0
		
	}
    public enum GameButton
    {
        UNKNOWN,UP,DOWN,LEFT,RIGHT,UP_L,UP_R,DOWN_L,DOWN_R,WEAK,MEDIUM,STRONG,DASHB,DASHF
    }
}

